version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - postgres
    volumes:
      - ./internal/migrations:/flyway/sql  # Указываем путь к миграциям
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/mydatabase
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: password
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate

  notification:
    build: .  # Собираем образ из Dockerfile
    container_name: notification
    depends_on:
      - postgres
    ports:
      - "8080:8080"  # Пробрасываем порт приложения
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - ./internal/templates:/app/templates  # Монтируем шаблоны, если они нужны