version: '3.8'

services:
  notification-service:
    build: .
    container_name: notification-service
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
      - ./.env:/app/.env