name: Deploy Notification Service CI/CD

on:
  push:
    branches: [ "mainReadyTrade", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/Notification"

      - name: Check Docker installation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/Notification
            
            # Проверка версии Docker и Docker Compose
            docker --version
            which docker-compose || echo "docker-compose not found"
            docker compose version || echo "docker compose not found"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/Notification
            
            # Create .env file
              echo "${{ secrets.ENV}}" > .env
              chmod 600 .env
            
            # Проверяем существование файла docker-compose
            if [ ! -f "docker-compose.yml" ]; then
              echo "docker-compose.yml not found!"
              ls -la
              exit 1
            fi
            
            # Используем docker-compose вместо docker compose, если доступен
            if command -v docker-compose &> /dev/null; then
              # Stop all running containers
              docker-compose down
            
              # Build the containers
              docker-compose build
            
              # Start containers
              docker-compose up -d
            
              # Check status
              sleep 5
              docker-compose ps
            else
              # Попытаемся использовать docker compose (новый синтаксис)
              # Stop all running containers
              docker compose down
            
              # Build the containers
              docker compose build
            
              # Start containers
              docker compose up -d
            
              # Check status
              sleep 5
              docker compose ps
            fi
